[auth]
authentication_enabled = false
strategy = "none"
current_user_method = "current_user"
authenticate_user_method = "authenticate_user!"
authorization_enabled = false
authorization_coordinator_class = "Tasker::Authorization::BaseCoordinator"
