[backoff]
default_backoff_seconds = [1, 2, 4, 8, 16, 32]
max_backoff_seconds = 300
backoff_multiplier = 2.0
jitter_enabled = true
jitter_max_percentage = 0.1
default_reenqueue_delay = 30
buffer_seconds = 5

[backoff.reenqueue_delays]
# TAS-41: New state machine states
initializing = 5
enqueuing_steps = 0
steps_in_process = 10
evaluating_results = 5
waiting_for_dependencies = 45
waiting_for_retry = 30
blocked_by_failures = 60