[database]
enable_secondary_database = false
url = "${DATABASE_URL}"
adapter = "postgresql"
encoding = "unicode"
host = "localhost"
username = "tasker"
password = "tasker"
checkout_timeout = 10
reaping_frequency = 10
skip_migration_check = false

[database.pool]
max_connections = 30
min_connections = 8
acquire_timeout_seconds = 30
idle_timeout_seconds = 300
max_lifetime_seconds = 3600

[database.variables]
statement_timeout = 5000
