[engine]
task_handler_directory = "tasks"
task_config_directory = "tasker/tasks"
identity_strategy = "default"
custom_events_directories = [ "config/tasker/events",]

[task_templates]
search_paths = [ "config/task_templates/*.{yml,yaml}", "config/tasks/*.{yml,yaml}",]

[dependency_graph]
max_depth = 50
cycle_detection_enabled = true
optimization_enabled = true

[events]
batch_size = 100
enabled = true
batch_timeout_ms = 1000

[cache]
enabled = true
ttl_seconds = 3600
max_size = 10000

[reenqueue]
has_ready_steps = 1
waiting_for_dependencies = 5
processing = 2
