[query_cache]
enabled = true
cleanup_interval_seconds = 300
memory_pressure_threshold = 0.8

[query_cache.active_workers]
ttl_seconds = 30
max_entries = 1000

[query_cache.worker_health]
ttl_seconds = 10
max_entries = 500

[query_cache.task_metadata]
ttl_seconds = 300
max_entries = 2000

[query_cache.handler_metadata]
ttl_seconds = 600
max_entries = 100
