# Worker Web API configuration
# Separate from orchestration web API (different port)

bind_address = "0.0.0.0:8081"  # Worker uses port 8081 (orchestration uses 8080)
request_timeout_seconds = 30
cors_enabled = true
cors_allowed_origins = ["*"]

# Health check endpoints
[health_endpoints]
enabled = true
readiness_path = "/health/ready"
liveness_path = "/health/live"
comprehensive_path = "/health"

# Metrics endpoint configuration
[metrics]
enabled = true
path = "/metrics"
format = "prometheus"  # prometheus or json

# API rate limiting
[rate_limiting]
enabled = false
requests_per_second = 100
burst_size = 200

# TLS configuration (optional)
[tls]
enabled = false
cert_path = ""
key_path = ""