services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres-extensions
    environment:
      POSTGRES_DB: tasker_rust_test
      POSTGRES_USER: tasker
      POSTGRES_PASSWORD: tasker
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      # Persist data across restarts
      - postgres_data:/var/lib/postgresql/data
      # Optional: mount custom initialization scripts
      - ./docker/init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasker -d tasker_rust_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_messages=info
      -c log_connections=on
      -c log_disconnections=on

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: tasker-dev