[database]
# Legacy pool_size removed - now using structured pool configuration below
checkout_timeout = 5
reaping_frequency = 10
prepared_statements = true
statement_cache_size = 100

[database.pool]
max_connections = 50
min_connections = 10
acquire_timeout_seconds = 30
idle_timeout_seconds = 300
max_lifetime_seconds = 3600
