# Test Environment Event Systems Configuration Overrides
#
# This file provides test-specific overrides for the unified event system configurations.
# It merges with the base configuration from config/tasker/base/event_systems.toml

# ============================================================================
# ORCHESTRATION EVENT SYSTEM - TEST OVERRIDES
# ============================================================================

[event_systems.orchestration]
namespaces = ["orchestration"]

# Faster timing for tests
[event_systems.orchestration.timing]
health_check_interval_seconds = 10
fallback_polling_interval_seconds = 1
visibility_timeout_seconds = 10
processing_timeout_seconds = 10
claim_timeout_seconds = 60

# Lower concurrency for test environments
[event_systems.orchestration.processing]
max_concurrent_operations = 5
batch_size = 5

# ============================================================================
# TASK READINESS EVENT SYSTEM - TEST OVERRIDES
# ============================================================================

[event_systems.task_readiness]
# Test with specific namespaces
namespaces = ["orchestration"]

# Faster timing for tests
[event_systems.task_readiness.timing]
health_check_interval_seconds = 10
fallback_polling_interval_seconds = 1
visibility_timeout_seconds = 10
processing_timeout_seconds = 10
claim_timeout_seconds = 60

# Lower concurrency for test environments
[event_systems.task_readiness.processing]
max_concurrent_operations = 20
batch_size = 10

# ============================================================================
# WORKER EVENT SYSTEM - TEST OVERRIDES
# ============================================================================

[event_systems.worker]
# Test with specific namespaces
namespaces = [
    "diamond_workflow",
    "linear_workflow",
    "mixed_dag_workflow",
    "order_fulfillment",
    "tree_workflow",
]

# Faster timing for tests
[event_systems.worker.timing]
health_check_interval_seconds = 10
fallback_polling_interval_seconds = 1
visibility_timeout_seconds = 10
processing_timeout_seconds = 10
claim_timeout_seconds = 60

# Lower concurrency for test environments
[event_systems.worker.processing]
max_concurrent_operations = 5
batch_size = 5

# Test-specific worker metadata
[event_systems.worker.metadata.in_process_events]
broadcast_buffer_size = 500
ffi_integration_enabled = true
queue_names = [
    "worker_diamond_workflow_queue",
    "worker_linear_workflow_queue",
    "worker_mixed_dag_workflow_queue",
    "worker_order_fulfillment_queue",
    "worker_tree_workflow_queue",
]
deduplication_cache_size = 500

[event_systems.worker.metadata.listener]
retry_interval_seconds = 2
max_retry_attempts = 2

[event_systems.worker.metadata.fallback_poller]
enabled = true
polling_interval_ms = 500
batch_size = 5
age_threshold_seconds = 1
max_age_hours = 1
visibility_timeout_seconds = 10

[event_systems.worker.metadata.resource_limits]
max_memory_mb = 512
max_cpu_percent = 50.0
max_database_connections = 5
max_queue_connections = 3
