[executor_pools.coordinator]
target_utilization = 0.65
scaling_interval_seconds = 15
health_check_interval_seconds = 5
scaling_cooldown_seconds = 15

[executor_pools.task_request_processor]
min_executors = 2
max_executors = 8
polling_interval_ms = 100
batch_size = 10
processing_timeout_ms = 30000

[executor_pools.task_claimer]
min_executors = 2
max_executors = 10
polling_interval_ms = 75
batch_size = 25
processing_timeout_ms = 30000

[executor_pools.step_enqueuer]
min_executors = 2
max_executors = 10
polling_interval_ms = 75
batch_size = 50
processing_timeout_ms = 30000

[executor_pools.step_result_processor]
min_executors = 2
max_executors = 12
polling_interval_ms = 100
batch_size = 20
processing_timeout_ms = 30000

[executor_pools.task_finalizer]
min_executors = 1
max_executors = 6
polling_interval_ms = 200
batch_size = 10
processing_timeout_ms = 30000
