[pgmq]
poll_interval_ms = 200
visibility_timeout_seconds = 60
batch_size = 3
max_retries = 2
shutdown_timeout_seconds = 10
default_namespaces = [ "dev_default", "dev_fulfillment", "dev_inventory", "dev_notifications", "linear_workflow", "tree_workflow",]
