# Development Environment Queue Configuration Overrides

# Development-specific backend settings for PGMQ
[queues.pgmq]
poll_interval_ms = 200
shutdown_timeout_seconds = 10
max_retries = 2

# Override universal queue settings for development
default_visibility_timeout_seconds = 60
default_batch_size = 3
