[telemetry]
enabled = true
service_name = "tasker-core-dev"
sample_rate = 1.0

[health]
enabled = true
check_interval_seconds = 30

[health.alert_thresholds]
error_rate = 0.1
queue_depth = 100.0

[events]
batch_size = 10
enabled = true
batch_timeout_ms = 500

[cache]
enabled = true
ttl_seconds = 300
max_size = 1000

[query_cache]
enabled = true
cleanup_interval_seconds = 60
memory_pressure_threshold = 0.7

[query_cache.active_workers]
ttl_seconds = 10
max_entries = 100

[query_cache.worker_health]
ttl_seconds = 5
max_entries = 50

[query_cache.task_metadata]
ttl_seconds = 60
max_entries = 500

[query_cache.handler_metadata]
ttl_seconds = 300
max_entries = 50
