name: 'Install Build Tools'
description: 'Installs cargo-binstall and common tools used across CI workflows'
author: 'Tasker Systems'

inputs:
  tools:
    description: 'Space-separated list of tools to install (nextest, sqlx-cli, audit)'
    required: false
    default: 'sqlx-cli'

runs:
  using: 'composite'
  steps:
    - name: Install cargo-binstall
      shell: bash
      run: |
        echo "📦 Installing cargo-binstall..."
        # Check if cargo-binstall is already installed
        if ! command -v cargo-binstall &> /dev/null; then
          # Install cargo-binstall using the official installer
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

          # Add cargo bin to PATH if not already there
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        else
          echo "cargo-binstall is already installed"
        fi

        # Verify installation
        cargo binstall --version

    - name: Install requested tools
      shell: bash
      run: |
        echo "🔧 Installing tools: ${{ inputs.tools }}"

        # Install tools based on input
        if echo "${{ inputs.tools }}" | grep -q "nextest"; then
          echo "Installing cargo-nextest..."
          cargo binstall cargo-nextest -y
        fi

        if echo "${{ inputs.tools }}" | grep -q "sqlx-cli"; then
          echo "Installing sqlx-cli..."
          cargo binstall sqlx-cli --no-default-features --features rustls,postgres -y
        fi

        if echo "${{ inputs.tools }}" | grep -q "audit"; then
          echo "Installing cargo-audit..."
          cargo binstall cargo-audit -y
        fi

        if echo "${{ inputs.tools }}" | grep -q "llvm-cov"; then
          echo "Installing cargo-llvm-cov..."
          cargo binstall cargo-llvm-cov -y
        fi

        echo "✅ Tool installation complete"

    - name: Display installed tools
      shell: bash
      run: |
        echo "📋 Installed tool versions:"
        if command -v cargo-nextest &> /dev/null; then
          echo "- cargo-nextest: $(cargo nextest --version | head -n1)"
        fi
        if command -v sqlx &> /dev/null; then
          echo "- sqlx-cli: $(sqlx --version)"
        fi
        if command -v cargo-audit &> /dev/null; then
          echo "- cargo-audit: $(cargo audit --version)"
        fi
        if command -v cargo-llvm-cov &> /dev/null; then
          echo "- cargo-llvm-cov: $(cargo llvm-cov --version)"
        fi
