name: "Install Build Tools"
description: "Installs cargo-binstall and common tools used across CI workflows"
author: "Tasker Systems"

inputs:
  tools:
    description: "Space-separated list of tools to install (nextest, sqlx-cli, audit, llvm-cov)"
    required: false
    default: "sqlx-cli"
  pin-versions:
    description: "Whether to pin tool versions for reproducible builds"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Cache cargo tools
      uses: actions/cache@v4
      id: cargo-tools-cache
      with:
        path: ~/.cargo/bin
        key: cargo-tools-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.tools }}
        restore-keys: |
          cargo-tools-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-
          cargo-tools-${{ runner.os }}-
    - name: Install cargo-binstall
      if: steps.cargo-tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "📦 Installing cargo-binstall..."
        # Check if cargo-binstall is already installed
        if ! command -v cargo-binstall &> /dev/null; then
          # Install cargo-binstall using direct binary download
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"

          # Determine platform
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            TARGET="universal-apple-darwin"
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            TARGET="x86_64-pc-windows-msvc"
          else
            TARGET="x86_64-unknown-linux-musl"
          fi

          # Download and extract
          echo "Downloading cargo-binstall for $TARGET..."
          curl -L --proto '=https' --tlsv1.2 -sSf \
            "https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-${TARGET}.tgz" | \
            tar -xz

          # Install to cargo bin directory
          mkdir -p "$HOME/.cargo/bin"
          mv cargo-binstall "$HOME/.cargo/bin/"
          chmod +x "$HOME/.cargo/bin/cargo-binstall"

          # Clean up
          cd ..
          rm -rf "$TEMP_DIR"
        else
          echo "cargo-binstall is already installed"
        fi

        # Verify installation
        if ! cargo binstall --version; then
          echo "❌ Failed to install cargo-binstall"
          exit 1
        fi
        echo "✅ cargo-binstall installed successfully"

    - name: Add cargo bin to PATH
      shell: bash
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Verify tools after cache restore
      if: steps.cargo-tools-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "📋 Verifying cached tools..."
        if ! command -v cargo-binstall &> /dev/null; then
          echo "❌ cargo-binstall not found in cache, will need to reinstall"
          exit 1
        fi
        echo "✅ cargo-binstall available from cache"

    - name: Install requested tools
      if: steps.cargo-tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Installing tools: ${{ inputs.tools }}"

        # Function to install tool with version pinning and fallback
        install_tool() {
          local tool_name="$1"
          local versioned_args="$2"
          local fallback_args="$3"

          echo "Installing $tool_name..."

          # Try versioned install first if pin-versions is true
          if [[ "${{ inputs.pin-versions }}" == "true" ]]; then
            echo "  Attempting versioned install: $versioned_args"
            if cargo binstall $versioned_args -y; then
              echo "✅ $tool_name installed successfully (pinned version)"
              return 0
            else
              echo "⚠️  Versioned install failed, trying fallback..."
            fi
          fi

          # Fallback to latest version
          echo "  Installing latest version: $fallback_args"
          if cargo binstall $fallback_args -y; then
            echo "✅ $tool_name installed successfully (latest version)"
          else
            echo "❌ Failed to install $tool_name"
            exit 1
          fi
        }

        # Install tools based on input with version pinning
        if echo "${{ inputs.tools }}" | grep -q "nextest"; then
          install_tool "cargo-nextest" \
            "cargo-nextest@0.9.67" \
            "cargo-nextest"
        fi

        if echo "${{ inputs.tools }}" | grep -q "sqlx-cli"; then
          install_tool "sqlx-cli" \
            "sqlx-cli@0.7.3 --no-default-features --features rustls,postgres" \
            "sqlx-cli --no-default-features --features rustls,postgres"
        fi

        if echo "${{ inputs.tools }}" | grep -q "audit"; then
          install_tool "cargo-audit" \
            "cargo-audit@0.18.3" \
            "cargo-audit"
        fi

        if echo "${{ inputs.tools }}" | grep -q "llvm-cov"; then
          install_tool "cargo-llvm-cov" \
            "cargo-llvm-cov@0.6.4" \
            "cargo-llvm-cov"
        fi

        echo "✅ All tool installations complete"

    - name: Display installed tools
      shell: bash
      run: |
        echo "📋 Installed tool versions:"
        if command -v cargo-nextest &> /dev/null; then
          echo "- cargo-nextest: $(cargo nextest --version | head -n1)"
        fi
        if command -v sqlx &> /dev/null; then
          echo "- sqlx-cli: $(sqlx --version)"
        fi
        if command -v cargo-audit &> /dev/null; then
          echo "- cargo-audit: $(cargo audit --version)"
        fi
        if command -v cargo-llvm-cov &> /dev/null; then
          echo "- cargo-llvm-cov: $(cargo llvm-cov --version)"
        fi
