name: "Install Build Tools"
description: "Installs cargo-binstall and common tools used across CI workflows"
author: "Tasker Systems"

inputs:
  tools:
    description: "Space-separated list of tools to install (nextest, sqlx-cli, audit, llvm-cov)"
    required: false
    default: "sqlx-cli"

runs:
  using: "composite"
  steps:
    - name: Cache cargo tools
      uses: actions/cache@v4
      id: cargo-tools-cache
      with:
        path: ~/.cargo/bin
        key: cargo-tools-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.tools }}
        restore-keys: |
          cargo-tools-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-
          cargo-tools-${{ runner.os }}-
    - name: Install cargo-binstall
      if: steps.cargo-tools-cache.outputs.cache-hit != 'true'
      uses: cargo-bins/cargo-binstall@main

    - name: Add cargo bin to PATH
      shell: bash
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Verify tools after cache restore
      if: steps.cargo-tools-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "📋 Verifying cached tools..."
        # List what tools we have in cache
        for tool in cargo-nextest sqlx cargo-audit cargo-llvm-cov; do
          if command -v "$tool" &> /dev/null; then
            echo "✅ $tool available from cache"
          fi
        done

    - name: Install requested tools
      if: steps.cargo-tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Installing tools: ${{ inputs.tools }}"

        # Install tools using proven working commands
        if echo "${{ inputs.tools }}" | grep -q "nextest"; then
          echo "Installing cargo-nextest with binstall --secure..."
          if ! cargo binstall cargo-nextest --secure -y; then
            echo "❌ Failed to install cargo-nextest"
            exit 1
          fi
          echo "✅ cargo-nextest installed successfully"
        fi

        if echo "${{ inputs.tools }}" | grep -q "sqlx-cli"; then
          echo "Installing sqlx-cli with cargo install..."
          if ! cargo install sqlx-cli --no-default-features --features native-tls,postgres; then
            echo "❌ Failed to install sqlx-cli"
            exit 1
          fi
          echo "✅ sqlx-cli installed successfully"
        fi

        if echo "${{ inputs.tools }}" | grep -q "audit"; then
          echo "Installing cargo-audit with cargo install --locked..."
          if ! cargo install cargo-audit --locked; then
            echo "❌ Failed to install cargo-audit"
            exit 1
          fi
          echo "✅ cargo-audit installed successfully"
        fi

        if echo "${{ inputs.tools }}" | grep -q "llvm-cov"; then
          echo "Installing cargo-llvm-cov with binstall..."
          if ! cargo binstall cargo-llvm-cov -y; then
            echo "❌ Failed to install cargo-llvm-cov"
            exit 1
          fi
          echo "✅ cargo-llvm-cov installed successfully"
        fi

        echo "✅ All tool installations complete"

    - name: Display installed tools
      shell: bash
      run: |
        echo "📋 Installed tool versions:"
        if command -v cargo-nextest &> /dev/null; then
          echo "- cargo-nextest: $(cargo nextest --version | head -n1)"
        fi
        if command -v sqlx &> /dev/null; then
          echo "- sqlx-cli: $(sqlx --version)"
        fi
        if command -v cargo-audit &> /dev/null; then
          echo "- cargo-audit: $(cargo audit --version)"
        fi
        if command -v cargo-llvm-cov &> /dev/null; then
          echo "- cargo-llvm-cov: $(cargo llvm-cov --version)"
        fi
