[package]
name = "pgmq-notify"
version = "0.1.0"
edition = "2021"
authors = ["Pete Taylor <pete.jc.taylor@hey.com>"]
description = "PG Notify layer for PGMQ"
license = "MIT"

[lib]
name = "pgmq_notify"
crate-type = ["rlib"]


[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

# Database and ORM
sqlx = { workspace = true, optional = true }
pgmq = { workspace = true }
rust_decimal = { workspace = true }
bigdecimal = { workspace = true }
uuid = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }

# Time and date handling
chrono = { workspace = true }

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# System information
sysinfo = { workspace = true }

# Logging and telemetry
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
structured-logger = { workspace = true }

# Configuration
config = { workspace = true }
regex = { workspace = true }
dotenvy = { workspace = true } # For loading .env files

# Random number generation
fastrand = { workspace = true }

# Development and testing
criterion = { workspace = true, optional = true }
rand = { workspace = true }
workspace_tools = { workspace = true }

[dev-dependencies]
# Testing tools
tokio-test = { workspace = true }
tempfile = { workspace = true }
proptest = { workspace = true }
insta = { workspace = true }
mockall = { workspace = true }
factori = { workspace = true }
url = { workspace = true }
serial_test = { workspace = true }
nextest = { workspace = true }

# Coverage tools (used in CI)
cargo-llvm-cov = { workspace = true }

[features]
default = []
