name: "Generate Test Configuration"
description: "Generates orchestration and worker configuration for tests"
author: "Tasker Systems"

inputs:
  database-url:
    description: "Database URL for configuration generation"
    required: false
    default: "postgresql://tasker:tasker@localhost:5432/tasker_rust_test"

runs:
  using: "composite"
  steps:
    - name: Generate test configuration
      shell: bash
      env:
        DATABASE_URL: ${{ inputs.database-url }}
      run: |
        mkdir -p config/tasker/generated

        echo "🔧 Generating orchestration configuration..."
        cargo run --package tasker-client --bin tasker-cli -- config generate \
          --context orchestration \
          --environment test \
          --source-dir config/tasker \
          --output config/tasker/generated/orchestration-test.toml

        echo "🔧 Generating worker configuration..."
        cargo run --package tasker-client --bin tasker-cli -- config generate \
          --context worker \
          --environment test \
          --source-dir config/tasker \
          --output config/tasker/generated/worker-test.toml

        echo "✅ Test configuration generated"
        ls -la config/tasker/generated/
