# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in tasker-core-rb.gemspec
gemspec

group :development, :test do
  gem 'benchmark-ips', '~> 2.0'
  gem 'bundler-audit', '~> 0.9'
  gem 'memory_profiler', '~> 1.0'
  gem 'rake-compiler', '~> 1.2.0'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
  gem 'ruby-prof', '~> 1.0'
  gem 'yard', '~> 0.9'
end

group :test do
  gem 'dotenv', '~> 2.8'
  gem 'pg', '~> 1.5'  # PostgreSQL client for pgmq
  gem 'simplecov', '~> 0.22'
  gem 'timecop', '~> 0.9'
  gem 'webmock', '~> 3.18'
end

# Development tools
group :development do
  gem 'guard', '~> 2.18'
  gem 'guard-rspec', '~> 4.7'
  gem 'pry', '~> 0.14'
  gem 'pry-byebug', '~> 3.10'
  gem 'rerun', '~> 0.14'
end
