# Tasker Core Configuration - Test Environment
# This configuration file provides test-specific overrides

auth:
  authentication_enabled: false
  strategy: "none"
  current_user_method: "current_user"
  authenticate_user_method: "authenticate_user!"
  authorization_enabled: false
  authorization_coordinator_class: "Tasker::Authorization::BaseCoordinator"

database:
  enable_secondary_database: false
  url: "${DATABASE_URL}"
  pool:
    max_connections: 10  # Reasonable for test environment
    min_connections: 2
    acquire_timeout_seconds: 2  # FAIL FAST: 2 second timeout for tests
    idle_timeout_seconds: 30   # Shorter idle timeout for tests
    max_lifetime_seconds: 300  # Shorter lifetime for tests

telemetry:
  enabled: false
  service_name: "tasker-core-rs-test"
  sample_rate: 1.0

engine:
  task_handler_directory: "tasks"
  task_config_directory: "tasker/tasks"
  identity_strategy: "default"
  custom_events_directories:
    - "config/tasker/events"

health:
  enabled: false  # Disable health checks in tests
  check_interval_seconds: 60
  alert_thresholds:
    error_rate: 0.05
    queue_depth: 1000.0

dependency_graph:
  max_depth: 50
  cycle_detection_enabled: true
  optimization_enabled: true

system:
  default_dependent_system_id: 1
  default_queue_name: "default"
  version: "1.0.0-test"

backoff:
  default_backoff_seconds: [1, 2, 4, 8, 16, 32]
  max_backoff_seconds: 300
  backoff_multiplier: 2.0
  jitter_enabled: true
  jitter_max_percentage: 0.1
  reenqueue_delays:
    has_ready_steps: 0
    waiting_for_dependencies: 45
    processing: 10
  default_reenqueue_delay: 30
  buffer_seconds: 5

execution:
  max_concurrent_tasks: 10    # Reduced for test environment
  max_concurrent_steps: 50    # Reduced for test environment
  default_timeout_seconds: 300  # Reduced for faster tests
  step_execution_timeout_seconds: 60
  max_discovery_attempts: 3
  step_batch_size: 10

reenqueue:
  has_ready_steps: 1
  waiting_for_dependencies: 5
  processing: 2

events:
  batch_size: 100
  enabled: true
  batch_timeout_ms: 1000

cache:
  enabled: true
  ttl_seconds: 3600
  max_size: 10000