# Tasker Core Configuration - Test Environment
# This configuration file provides test-specific overrides

auth:
  authentication_enabled: false
  strategy: "none"
  current_user_method: "current_user"
  authenticate_user_method: "authenticate_user!"
  authorization_enabled: false
  authorization_coordinator_class: "Tasker::Authorization::BaseCoordinator"

database:
  enable_secondary_database: false
  url: "${DATABASE_URL}"
  pool:
    max_connections: 150  # High for test environment to avoid contention
    min_connections: 10
    acquire_timeout_seconds: 2  # FAIL FAST: 2 second timeout for tests
    idle_timeout_seconds: 30   # Shorter idle timeout for tests
    max_lifetime_seconds: 300  # Shorter lifetime for tests

telemetry:
  enabled: false
  service_name: "tasker-core-rs-test"
  sample_rate: 1.0

engine:
  task_handler_directory: "tasks"
  task_config_directory: "tasker/tasks"
  identity_strategy: "default"
  custom_events_directories:
    - "config/tasker/events"

health:
  enabled: false  # Disable health checks in tests
  check_interval_seconds: 60
  alert_thresholds:
    error_rate: 0.05
    queue_depth: 1000.0

dependency_graph:
  max_depth: 50
  cycle_detection_enabled: true
  optimization_enabled: true

system:
  default_dependent_system_id: 1
  default_queue_name: "default"
  version: "1.0.0-test"

backoff:
  default_backoff_seconds: [1, 2, 4, 8, 16, 32]
  max_backoff_seconds: 300
  backoff_multiplier: 2.0
  jitter_enabled: true
  jitter_max_percentage: 0.1
  reenqueue_delays:
    has_ready_steps: 0
    waiting_for_dependencies: 45
    processing: 10
  default_reenqueue_delay: 30
  buffer_seconds: 5

execution:
  environment: "test"           # Required environment field
  processing_mode: "pgmq"
  max_concurrent_tasks: 10    # Reduced for test environment
  max_concurrent_steps: 50    # Reduced for test environment
  default_timeout_seconds: 300  # Reduced for faster tests
  step_execution_timeout_seconds: 60
  max_discovery_attempts: 3
  step_batch_size: 10

reenqueue:
  has_ready_steps: 1
  waiting_for_dependencies: 5
  processing: 2

events:
  batch_size: 100
  enabled: true
  batch_timeout_ms: 1000

cache:
  enabled: true
  ttl_seconds: 60         # Shorter cache for tests
  max_size: 1000          # Smaller cache for tests

# Query caching configuration for test environment
query_cache:
  enabled: true
  # Worker query caching (test settings - rapid invalidation)
  active_workers:
    ttl_seconds: 1         # Cache active workers for only 1 second in tests
    max_entries: 100       # Smaller cache for test environment
  worker_health:
    ttl_seconds: 1         # Cache worker health for only 1 second in tests
    max_entries: 50        # Smaller cache for test environment
  task_metadata:
    ttl_seconds: 5         # Cache task metadata for only 5 seconds in tests
    max_entries: 200       # Smaller cache for test environment
  handler_metadata:
    ttl_seconds: 10        # Cache handler metadata for only 10 seconds in tests
    max_entries: 20        # Much smaller cache for test environment
  # Aggressive cache cleanup for tests
  cleanup_interval_seconds: 10   # Clean expired entries every 10 seconds
  memory_pressure_threshold: 0.5 # Clear cache at 50% to ensure fresh data

# pgmq configuration for PostgreSQL message queue orchestration
pgmq:
  poll_interval_seconds: 1        # Fast polling for test environment
  visibility_timeout_seconds: 30   # Standard visibility timeout
  batch_size: 5                    # Small batches for test predictability
  max_retries: 3                   # Standard retry limit
  default_namespaces:
    - default
    - fulfillment
    - inventory
    - notifications
  queue_naming_pattern: "{namespace}_queue"

# orchestration mode configuration
orchestration:
  mode: "embedded"                 # Use embedded mode for tests
  
  # Queue configuration for orchestration core
  queues:
    # Task request queue - handles incoming task requests from external systems
    task_requests: "task_requests_queue"
    
    # Task processing queue - holds tasks ready for orchestration processing
    task_processing: "task_processing_queue"
    
    # Batch results queue - collects completed batch execution results
    batch_results: "batch_results_queue"
    
    # Namespaced worker queues - workers poll these for step batches
    worker_queues:
      default: "default_queue"
      fulfillment: "fulfillment_queue"
      inventory: "inventory_queue"
      notifications: "notifications_queue"
    
    # Queue configuration parameters (test settings - fast processing)
    settings:
      visibility_timeout_seconds: 30
      message_retention_seconds: 3600    # 1 hour for tests
      dead_letter_queue_enabled: false   # Disable for cleaner test environment
      max_receive_count: 1               # Fail fast in tests
  
  embedded_orchestrator:
    auto_start: true               # Auto-start embedded orchestrator in tests
    namespaces: ["default", "fulfillment", "inventory", "notifications"]
    shutdown_timeout_seconds: 5   # Quick shutdown for tests

# TaskTemplate discovery configuration
task_templates:
  search_paths:
    test:
      - "spec/handlers/examples/**/config/*.{yml,yaml}"
      - "spec/fixtures/task_templates/*.{yml,yaml}"
    development:
      - "config/tasks/*.{yml,yaml}"
      - "config/tasker/tasks/*.{yml,yaml}"
      - "lib/tasks/*.{yml,yaml}"
    production:
      - "config/tasks/*.{yml,yaml}"
      - "config/tasker/tasks/*.{yml,yaml}"
  
  # Registry configuration
  registry:
    auto_register: true           # Auto-register discovered templates
    validate_on_load: true        # Validate templates when loading
    fail_on_invalid: false        # Continue loading even if some templates are invalid
