[auth]
authentication_enabled = true
strategy = "jwt"
current_user_method = "current_authenticated_user"
authenticate_user_method = "authenticate_user_required!"
authorization_enabled = true
authorization_coordinator_class = "Tasker::Authorization::ProductionCoordinator"
