[executor_pools.coordinator]
target_utilization = 0.8
scaling_interval_seconds = 30
health_check_interval_seconds = 15
scaling_cooldown_seconds = 60

[executor_pools.task_request_processor]
min_executors = 3
max_executors = 15
polling_interval_ms = 200
batch_size = 20
processing_timeout_ms = 60000

[executor_pools.task_claimer]
min_executors = 5
max_executors = 20
polling_interval_ms = 100
batch_size = 50
processing_timeout_ms = 60000

[executor_pools.step_enqueuer]
min_executors = 5
max_executors = 15
polling_interval_ms = 100
batch_size = 100
processing_timeout_ms = 60000

[executor_pools.step_result_processor]
min_executors = 3
max_executors = 20
polling_interval_ms = 200
batch_size = 30
processing_timeout_ms = 60000

[executor_pools.task_finalizer]
min_executors = 2
max_executors = 10
polling_interval_ms = 500
batch_size = 15
processing_timeout_ms = 60000
