# Production Environment - MPSC Channel Configuration Overrides
#
# This file provides production-specific overrides for MPSC channel buffer sizes.
# These values are optimized for production workloads with higher throughput and
# larger notification bursts.

# ============================================================================
# ORCHESTRATION CHANNELS - PRODUCTION OVERRIDES
# ============================================================================

[mpsc_channels.orchestration.command_processor]
# Larger buffer for production orchestration command load
command_buffer_size = 5000

[mpsc_channels.orchestration.event_listeners]
# Much larger buffer to handle production notification bursts
# Production workloads can generate 10k+ notifications during bulk task creation
pgmq_event_buffer_size = 50000

# ============================================================================
# TASK READINESS CHANNELS - PRODUCTION OVERRIDES
# ============================================================================

[mpsc_channels.task_readiness.event_channel]
# Increased capacity for production task readiness events
buffer_size = 5000

# ============================================================================
# WORKER CHANNELS - PRODUCTION OVERRIDES
# ============================================================================

[mpsc_channels.worker.command_processor]
# Increased worker command buffer for production concurrency
command_buffer_size = 2000

[mpsc_channels.worker.in_process_events]
# Larger broadcast buffer for production FFI event volume
broadcast_buffer_size = 2000

# ============================================================================
# SHARED/CROSS-CUTTING CHANNELS - PRODUCTION OVERRIDES
# ============================================================================

[mpsc_channels.shared.event_publisher]
# Larger event publishing queue for production event volume
event_queue_buffer_size = 10000
