# Production Environment Queue Configuration Overrides

[queues]
# Production-specific namespaces for enterprise features
default_namespaces = [
    "diamond_workflow",
    "mixed_dag_workflow",
    "order_fulfillment",
    "linear_workflow",
    "tree_workflow",
]

# Production-specific backend settings for PGMQ
[queues.pgmq]
poll_interval_ms = 500
shutdown_timeout_seconds = 60
max_retries = 5

# Override universal queue settings for production
default_visibility_timeout_seconds = 300
default_batch_size = 20
