# TAS-43 Task Readiness Configuration - Production Environment  
# Production-specific overrides for task readiness system

[task_readiness]
# Start with hybrid mode for safe production rollout
deployment_mode = "hybrid"

[task_readiness.enhanced_settings]
# Production-ready timeouts
startup_timeout_seconds = 60
shutdown_timeout_seconds = 30

# Enable metrics for production monitoring
metrics_enabled = true

# Conservative rollback threshold for production stability
rollback_threshold_percent = 10.0

[task_readiness.notification.connection]
# Stable connection handling for production
health_check_interval_seconds = 60
max_connection_retries = 5
connection_retry_delay_seconds = 5

[task_readiness.fallback_polling]
# Conservative polling for production
polling_interval_ms = 5000
age_threshold_seconds = 10
max_age_seconds = 7200  # 2 hours max for production
batch_size = 100
max_concurrent_pollers = 4

# Event channel configuration
# NOTE: buffer_size and send_timeout_ms MOVED to mpsc_channels.toml (TAS-51)
[task_readiness.event_channel]
# More retries for production reliability
max_retries = 5

[task_readiness.event_channel.backoff]
# Production-appropriate backoff
initial_delay_ms = 500
max_delay_ms = 30000  # 30 seconds max
multiplier = 2.0
jitter_percent = 0.2

[task_readiness.coordinator]
# Production coordinator settings
max_concurrent_operations = 500
operation_timeout_ms = 10000
stats_interval_seconds = 300  # 5 minutes

[task_readiness.error_handling]
# Production error thresholds
max_consecutive_errors = 20
error_rate_threshold_per_minute = 10
# NOTE: Circuit breaker configuration moved to circuit_breakers.toml