[telemetry]
enabled = true
service_name = "tasker-core-rs-prod"
sample_rate = 0.1

[health]
enabled = true
check_interval_seconds = 120

[events]
batch_size = 500
enabled = true
batch_timeout_ms = 5000

[cache]
enabled = true
ttl_seconds = 7200
max_size = 50000

[query_cache]
enabled = true
cleanup_interval_seconds = 600
memory_pressure_threshold = 0.85

[health.alert_thresholds]
error_rate = 0.02
queue_depth = 5000.0

[query_cache.active_workers]
ttl_seconds = 60
max_entries = 5000

[query_cache.worker_health]
ttl_seconds = 30
max_entries = 2000

[query_cache.task_metadata]
ttl_seconds = 600
max_entries = 10000

[query_cache.handler_metadata]
ttl_seconds = 3600
max_entries = 500
